CREATE DATABASE IF NOT EXISTS looking_for;
USE looking_for;

CREATE TABLE IF NOT EXISTS buscas (
    id_busca INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    texto VARCHAR(255) NOT NULL,
    distance INT(11) NOT NULL,
    price INT(11) NOT NULL,
    grade INT(11) NOT NULL,
    data TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS escolhas (
    id_escolha INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    posicao INT(11) NOT NULL,
    data TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);